# README ------------------------------------------------------------------
# This script does the best subset selection of models; the selecting criteria is the AIC score.
# Two general rules are consider: 1) use consecutive lags; 2) 10 observations for each predictor, hence:
sample_per_predictor <- 10




# Lag Variables -----------------------------------------------------------
for (lag_length in 1:10) {
  sample_size <- nrow(d) - lag_length
  max_predictors <- floor(sample_size / sample_per_predictor)
  max_predictor_sets <- floor(max_predictors / lag_length)
  
  start <- 1 + lag_length
  end <- dim(d)[1]
  
  for (i in 1:lag_length) {
    assign(paste0("c_lag", as.character(i)), c[(start-i) : (end-i)])
    assign(paste0("v_lag", as.character(i)), v[(start-i) : (end-i)])
    assign(paste0("a_lag", as.character(i)), a[(start-i) : (end-i)])
    assign(paste0("n_lag", as.character(i)), n[(start-i) : (end-i)])
    assign(paste0("p_lag", as.character(i)), p[(start-i) : (end-i)])
    assign(paste0("h_lag", as.character(i)), h[(start-i) : (end-i)])
    assign(paste0("dh_lag", as.character(i)), dh[(start-i) : (end-i)])
  }
  
  if (lag_length == 1) {
    d_lag1 <- data.frame(
      c = c[start : end], 
      c_lag1 = c_lag1, 
      v_lag1 = v_lag1, 
      a_lag1 = a_lag1, 
      n_lag1 = n_lag1, 
      p_lag1 = p_lag1, 
      h_lag1 = h_lag1, 
      dh_lag1 = dh_lag1
    )
  } else if (lag_length == 2) {
    d_lag2 <- data.frame(
      c = c[start : end], 
      c_lag1 = c_lag1, 
      c_lag2 = c_lag2, 
      v_lag1 = v_lag1, 
      v_lag2 = v_lag2, 
      a_lag1 = a_lag1, 
      a_lag2 = a_lag2, 
      n_lag1 = n_lag1, 
      n_lag2 = n_lag2, 
      p_lag1 = p_lag1, 
      p_lag2 = p_lag2, 
      h_lag1 = h_lag1, 
      h_lag2 = h_lag2, 
      dh_lag1 = dh_lag1, 
      dh_lag2 = dh_lag2
    )
  } else if (lag_length == 3) {
    d_lag3 <- data.frame(
      c = c[start : end], 
      c_lag1 = c_lag1, 
      c_lag2 = c_lag2, 
      c_lag3 = c_lag3, 
      v_lag1 = v_lag1, 
      v_lag2 = v_lag2, 
      v_lag3 = v_lag3, 
      a_lag1 = a_lag1, 
      a_lag2 = a_lag2, 
      a_lag3 = a_lag3, 
      n_lag1 = n_lag1, 
      n_lag2 = n_lag2, 
      n_lag3 = n_lag3, 
      p_lag1 = p_lag1, 
      p_lag2 = p_lag2, 
      p_lag3 = p_lag3, 
      h_lag1 = h_lag1, 
      h_lag2 = h_lag2, 
      h_lag3 = h_lag3, 
      dh_lag1 = dh_lag1, 
      dh_lag2 = dh_lag2, 
      dh_lag3 = dh_lag3
    )
  } else if (lag_length == 4) {
    d_lag4 <- data.frame(
      c = c[start : end], 
      c_lag1 = c_lag1, 
      c_lag2 = c_lag2, 
      c_lag3 = c_lag3, 
      c_lag4 = c_lag4, 
      v_lag1 = v_lag1, 
      v_lag2 = v_lag2, 
      v_lag3 = v_lag3, 
      v_lag4 = v_lag4,
      a_lag1 = a_lag1, 
      a_lag2 = a_lag2, 
      a_lag3 = a_lag3, 
      a_lag4 = a_lag4,
      n_lag1 = n_lag1, 
      n_lag2 = n_lag2, 
      n_lag3 = n_lag3, 
      n_lag4 = n_lag4,
      p_lag1 = p_lag1, 
      p_lag2 = p_lag2, 
      p_lag3 = p_lag3, 
      p_lag4 = p_lag4,
      h_lag1 = h_lag1, 
      h_lag2 = h_lag2, 
      h_lag3 = h_lag3, 
      h_lag4 = h_lag4,
      dh_lag1 = dh_lag1, 
      dh_lag2 = dh_lag2, 
      dh_lag3 = dh_lag3, 
      dh_lag4 = dh_lag4
    )
  } else if (lag_length == 5) {
    d_lag5 <- data.frame(
      c = c[start : end], 
      c_lag1 = c_lag1, 
      c_lag2 = c_lag2, 
      c_lag3 = c_lag3, 
      c_lag4 = c_lag4, 
      c_lag5 = c_lag5, 
      v_lag1 = v_lag1, 
      v_lag2 = v_lag2, 
      v_lag3 = v_lag3, 
      v_lag4 = v_lag4,
      v_lag5 = v_lag5,
      a_lag1 = a_lag1, 
      a_lag2 = a_lag2, 
      a_lag3 = a_lag3, 
      a_lag4 = a_lag4,
      a_lag5 = a_lag5,
      n_lag1 = n_lag1, 
      n_lag2 = n_lag2, 
      n_lag3 = n_lag3, 
      n_lag4 = n_lag4,
      n_lag5 = n_lag5,
      p_lag1 = p_lag1, 
      p_lag2 = p_lag2, 
      p_lag3 = p_lag3, 
      p_lag4 = p_lag4,
      p_lag5 = p_lag5,
      h_lag1 = h_lag1, 
      h_lag2 = h_lag2, 
      h_lag3 = h_lag3, 
      h_lag4 = h_lag4,
      h_lag5 = h_lag5,
      dh_lag1 = dh_lag1, 
      dh_lag2 = dh_lag2, 
      dh_lag3 = dh_lag3, 
      dh_lag4 = dh_lag4,
      dh_lag5 = dh_lag5
    )
  } else if (lag_length == 6) {
    d_lag6 <- data.frame(
      c = c[start : end], 
      c_lag1 = c_lag1, 
      c_lag2 = c_lag2, 
      c_lag3 = c_lag3, 
      c_lag4 = c_lag4, 
      c_lag5 = c_lag5, 
      c_lag6 = c_lag6, 
      v_lag1 = v_lag1, 
      v_lag2 = v_lag2, 
      v_lag3 = v_lag3, 
      v_lag4 = v_lag4,
      v_lag5 = v_lag5, 
      v_lag6 = v_lag6, 
      a_lag1 = a_lag1, 
      a_lag2 = a_lag2, 
      a_lag3 = a_lag3, 
      a_lag4 = a_lag4,
      a_lag5 = a_lag5, 
      a_lag6 = a_lag6, 
      n_lag1 = n_lag1, 
      n_lag2 = n_lag2, 
      n_lag3 = n_lag3, 
      n_lag4 = n_lag4,
      n_lag5 = n_lag5, 
      n_lag6 = n_lag6, 
      p_lag1 = p_lag1, 
      p_lag2 = p_lag2, 
      p_lag3 = p_lag3, 
      p_lag4 = p_lag4,
      p_lag5 = p_lag5, 
      p_lag6 = p_lag6, 
      h_lag1 = h_lag1, 
      h_lag2 = h_lag2, 
      h_lag3 = h_lag3, 
      h_lag4 = h_lag4,
      h_lag5 = h_lag5, 
      h_lag6 = h_lag6, 
      dh_lag1 = dh_lag1, 
      dh_lag2 = dh_lag2, 
      dh_lag3 = dh_lag3, 
      dh_lag4 = dh_lag4,
      dh_lag5 = dh_lag5, 
      dh_lag6 = dh_lag6
    )
  } else if (lag_length == 7) {
    d_lag7 <- data.frame(
      c = c[start : end], 
      c_lag1 = c_lag1, 
      c_lag2 = c_lag2, 
      c_lag3 = c_lag3, 
      c_lag4 = c_lag4, 
      c_lag5 = c_lag5, 
      c_lag6 = c_lag6, 
      c_lag7 = c_lag7, 
      v_lag1 = v_lag1, 
      v_lag2 = v_lag2, 
      v_lag3 = v_lag3, 
      v_lag4 = v_lag4,
      v_lag5 = v_lag5, 
      v_lag6 = v_lag6, 
      v_lag7 = v_lag7, 
      a_lag1 = a_lag1, 
      a_lag2 = a_lag2, 
      a_lag3 = a_lag3, 
      a_lag4 = a_lag4,
      a_lag5 = a_lag5, 
      a_lag6 = a_lag6, 
      a_lag7 = a_lag7, 
      n_lag1 = n_lag1, 
      n_lag2 = n_lag2, 
      n_lag3 = n_lag3, 
      n_lag4 = n_lag4,
      n_lag5 = n_lag5, 
      n_lag6 = n_lag6, 
      n_lag7 = n_lag7, 
      p_lag1 = p_lag1, 
      p_lag2 = p_lag2, 
      p_lag3 = p_lag3, 
      p_lag4 = p_lag4,
      p_lag5 = p_lag5, 
      p_lag6 = p_lag6, 
      p_lag7 = p_lag7, 
      h_lag1 = h_lag1, 
      h_lag2 = h_lag2, 
      h_lag3 = h_lag3, 
      h_lag4 = h_lag4,
      h_lag5 = h_lag5, 
      h_lag6 = h_lag6, 
      h_lag7 = h_lag7, 
      dh_lag1 = dh_lag1, 
      dh_lag2 = dh_lag2, 
      dh_lag3 = dh_lag3, 
      dh_lag4 = dh_lag4,
      dh_lag5 = dh_lag5, 
      dh_lag6 = dh_lag6, 
      dh_lag7 = dh_lag7
    )
  } else if (lag_length == 8) {
    d_lag8 <- data.frame(
      c = c[start : end], 
      c_lag1 = c_lag1, 
      c_lag2 = c_lag2, 
      c_lag3 = c_lag3, 
      c_lag4 = c_lag4, 
      c_lag5 = c_lag5, 
      c_lag6 = c_lag6, 
      c_lag7 = c_lag7, 
      c_lag8 = c_lag8, 
      v_lag1 = v_lag1, 
      v_lag2 = v_lag2, 
      v_lag3 = v_lag3, 
      v_lag4 = v_lag4,
      v_lag5 = v_lag5, 
      v_lag6 = v_lag6, 
      v_lag7 = v_lag7, 
      v_lag8 = v_lag8, 
      a_lag1 = a_lag1, 
      a_lag2 = a_lag2, 
      a_lag3 = a_lag3, 
      a_lag4 = a_lag4,
      a_lag5 = a_lag5, 
      a_lag6 = a_lag6, 
      a_lag7 = a_lag7, 
      a_lag8 = a_lag8, 
      n_lag1 = n_lag1, 
      n_lag2 = n_lag2, 
      n_lag3 = n_lag3, 
      n_lag4 = n_lag4,
      n_lag5 = n_lag5, 
      n_lag6 = n_lag6, 
      n_lag7 = n_lag7, 
      n_lag8 = n_lag8, 
      p_lag1 = p_lag1, 
      p_lag2 = p_lag2, 
      p_lag3 = p_lag3, 
      p_lag4 = p_lag4,
      p_lag5 = p_lag5, 
      p_lag6 = p_lag6, 
      p_lag7 = p_lag7, 
      p_lag8 = p_lag8, 
      h_lag1 = h_lag1, 
      h_lag2 = h_lag2, 
      h_lag3 = h_lag3, 
      h_lag4 = h_lag4,
      h_lag5 = h_lag5, 
      h_lag6 = h_lag6, 
      h_lag7 = h_lag7, 
      h_lag8 = h_lag8, 
      dh_lag1 = dh_lag1, 
      dh_lag2 = dh_lag2, 
      dh_lag3 = dh_lag3, 
      dh_lag4 = dh_lag4,
      dh_lag5 = dh_lag5, 
      dh_lag6 = dh_lag6, 
      dh_lag7 = dh_lag7, 
      dh_lag8 = dh_lag8
    )
  } else if (lag_length == 9) {
    d_lag9 <- data.frame(
      c = c[start : end], 
      c_lag1 = c_lag1, 
      c_lag2 = c_lag2, 
      c_lag3 = c_lag3, 
      c_lag4 = c_lag4, 
      c_lag5 = c_lag5, 
      c_lag6 = c_lag6, 
      c_lag7 = c_lag7, 
      c_lag8 = c_lag8, 
      c_lag9 = c_lag9, 
      v_lag1 = v_lag1, 
      v_lag2 = v_lag2, 
      v_lag3 = v_lag3, 
      v_lag4 = v_lag4,
      v_lag5 = v_lag5, 
      v_lag6 = v_lag6, 
      v_lag7 = v_lag7, 
      v_lag8 = v_lag8, 
      v_lag9 = v_lag9, 
      a_lag1 = a_lag1, 
      a_lag2 = a_lag2, 
      a_lag3 = a_lag3, 
      a_lag4 = a_lag4,
      a_lag5 = a_lag5, 
      a_lag6 = a_lag6, 
      a_lag7 = a_lag7, 
      a_lag8 = a_lag8, 
      a_lag9 = a_lag9, 
      n_lag1 = n_lag1, 
      n_lag2 = n_lag2, 
      n_lag3 = n_lag3, 
      n_lag4 = n_lag4,
      n_lag5 = n_lag5, 
      n_lag6 = n_lag6, 
      n_lag7 = n_lag7, 
      n_lag8 = n_lag8, 
      n_lag9 = n_lag9, 
      p_lag1 = p_lag1, 
      p_lag2 = p_lag2, 
      p_lag3 = p_lag3, 
      p_lag4 = p_lag4,
      p_lag5 = p_lag5, 
      p_lag6 = p_lag6, 
      p_lag7 = p_lag7, 
      p_lag8 = p_lag8, 
      p_lag9 = p_lag9, 
      h_lag1 = h_lag1, 
      h_lag2 = h_lag2, 
      h_lag3 = h_lag3, 
      h_lag4 = h_lag4,
      h_lag5 = h_lag5, 
      h_lag6 = h_lag6, 
      h_lag7 = h_lag7, 
      h_lag8 = h_lag8, 
      h_lag9 = h_lag9, 
      dh_lag1 = dh_lag1, 
      dh_lag2 = dh_lag2, 
      dh_lag3 = dh_lag3, 
      dh_lag4 = dh_lag4,
      dh_lag5 = dh_lag5, 
      dh_lag6 = dh_lag6, 
      dh_lag7 = dh_lag7, 
      dh_lag8 = dh_lag8, 
      dh_lag9 = dh_lag9
    )
  } else if (lag_length == 10) {
    d_lag10 <- data.frame(
      c = c[start : end], 
      c_lag1 = c_lag1, 
      c_lag2 = c_lag2, 
      c_lag3 = c_lag3, 
      c_lag4 = c_lag4, 
      c_lag5 = c_lag5, 
      c_lag6 = c_lag6, 
      c_lag7 = c_lag7, 
      c_lag8 = c_lag8, 
      c_lag9 = c_lag9, 
      c_lag10 = c_lag10, 
      v_lag1 = v_lag1, 
      v_lag2 = v_lag2, 
      v_lag3 = v_lag3, 
      v_lag4 = v_lag4,
      v_lag5 = v_lag5, 
      v_lag6 = v_lag6, 
      v_lag7 = v_lag7, 
      v_lag8 = v_lag8, 
      v_lag9 = v_lag9, 
      v_lag10 = v_lag10, 
      a_lag1 = a_lag1, 
      a_lag2 = a_lag2, 
      a_lag3 = a_lag3, 
      a_lag4 = a_lag4,
      a_lag5 = a_lag5, 
      a_lag6 = a_lag6, 
      a_lag7 = a_lag7, 
      a_lag8 = a_lag8, 
      a_lag9 = a_lag9, 
      a_lag10 = a_lag10, 
      n_lag1 = n_lag1, 
      n_lag2 = n_lag2, 
      n_lag3 = n_lag3, 
      n_lag4 = n_lag4,
      n_lag5 = n_lag5, 
      n_lag6 = n_lag6, 
      n_lag7 = n_lag7, 
      n_lag8 = n_lag8, 
      n_lag9 = n_lag9, 
      n_lag10 = n_lag10, 
      p_lag1 = p_lag1, 
      p_lag2 = p_lag2, 
      p_lag3 = p_lag3, 
      p_lag4 = p_lag4,
      p_lag5 = p_lag5, 
      p_lag6 = p_lag6, 
      p_lag7 = p_lag7, 
      p_lag8 = p_lag8, 
      p_lag9 = p_lag9, 
      p_lag10 = p_lag10, 
      h_lag1 = h_lag1, 
      h_lag2 = h_lag2, 
      h_lag3 = h_lag3, 
      h_lag4 = h_lag4,
      h_lag5 = h_lag5, 
      h_lag6 = h_lag6, 
      h_lag7 = h_lag7, 
      h_lag8 = h_lag8, 
      h_lag9 = h_lag9, 
      h_lag10 = h_lag10, 
      dh_lag1 = dh_lag1, 
      dh_lag2 = dh_lag2, 
      dh_lag3 = dh_lag3, 
      dh_lag4 = dh_lag4,
      dh_lag5 = dh_lag5, 
      dh_lag6 = dh_lag6, 
      dh_lag7 = dh_lag7, 
      dh_lag8 = dh_lag8, 
      dh_lag9 = dh_lag9, 
      dh_lag10 = dh_lag10
    )
  }
  
}


rm(list = c("start", "end", "lag_length", "max_predictors", "max_predictor_sets", "i", "sample_size", "sample_per_predictor"))
rm(list = c("c_lag1", "c_lag2", "c_lag3", "c_lag4", "c_lag5", "c_lag6", "c_lag7", "c_lag8", "c_lag9", "c_lag10"))
rm(list = c("v_lag1", "v_lag2", "v_lag3", "v_lag4", "v_lag5", "v_lag6", "v_lag7", "v_lag8", "v_lag9", "v_lag10"))
rm(list = c("a_lag1", "a_lag2", "a_lag3", "a_lag4", "a_lag5", "a_lag6", "a_lag7", "a_lag8", "a_lag9", "a_lag10"))
rm(list = c("n_lag1", "n_lag2", "n_lag3", "n_lag4", "n_lag5", "n_lag6", "n_lag7", "n_lag8", "n_lag9", "n_lag10"))
rm(list = c("p_lag1", "p_lag2", "p_lag3", "p_lag4", "p_lag5", "p_lag6", "p_lag7", "p_lag8", "p_lag9", "p_lag10"))
rm(list = c("h_lag1", "h_lag2", "h_lag3", "h_lag4", "h_lag5", "h_lag6", "h_lag7", "h_lag8", "h_lag9", "h_lag10"))
rm(list = c("dh_lag1", "dh_lag2", "dh_lag3", "dh_lag4", "dh_lag5", "dh_lag6", "dh_lag7", "dh_lag8", "dh_lag9", "dh_lag10"))