# This script samples statistics (mean, posterior interval) from the posterior distributions generated by the selected models in R script "./code/06_model.R"
par(mfrow = c(1, 1))


# M-110s: one predictor, ten lags -----------------------------------------
pairs(m.v10)
plot(precis(m.v10, prob=0.95), main = "Posterior Intervals (M-110s: Virus)")




# M-205s: two predictors, five lags ---------------------------------------
pairs(m.v5dh5)
plot(precis(m.v5dh5, prob=0.95), main = "Posterior Intervals (M-205s: Virus, DHCQ)")




# M-303s: three predictors, three lags ------------------------------------
pairs(m.v3a3dh3)
plot(precis(m.v3a3dh3, prob=0.95), main = "Posterior Intervals (M-303s: Virus, Acetaminophen, DHCQ)")

